import { Provider } from './types';

export const PROVIDERS: Provider[] = [
  {
    id: 'aws',
    name: 'AWS',
    displayName: 'AWS Infrastructure',
    userFacingName: 'Cloud Infrastructure',
    enables: 'Platform hosting, API routing, data storage across Singapore & Mumbai regions',
    statusPageUrl: 'https://health.aws.amazon.com/health/status',
    apiEndpoint: 'https://status.aws.amazon.com/data.json',
    color: '#ff9900',
    priority: 'primary',
    impacts: 'All research services may experience slowdowns or interruptions',
    regions: ['Singapore (ap-southeast-1)', 'Mumbai (ap-south-1)'],
    services: ['Lambda Functions', 'EC2 Instances', 'API Gateway', 'S3 Storage'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    displayName: 'OpenAI Services',
    userFacingName: 'Research Architecture & Data Collection',
    enables: 'Methodology design, data collection orchestration, quality validation',
    statusPageUrl: 'https://status.openai.com',
    apiEndpoint: 'https://status.openai.com/api/v2/summary.json',
    color: '#10a37f',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Research architecture and data collection workflows unavailable',
    models: ['GPT-5', 'GPT-5 mini', 'GPT-5-mini'],
    role: 'primary',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    displayName: 'Anthropic Services',
    userFacingName: 'Research Orchestration & Output Generation',
    enables: 'Project coordination, research brief creation, presentation generation',
    statusPageUrl: 'https://status.anthropic.com',
    apiEndpoint: 'https://status.anthropic.com/api/v2/summary.json',
    color: '#d4a574',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Research orchestration and output generation unavailable',
    models: ['Claude Sonnet 4', 'Claude Sonnet 4.5', 'Claude Haiku 4.5', 'Claude 4 Sonnet', 'Claude 4.5 Sonnet'],
    role: 'primary',
  },
  {
    id: 'google',
    name: 'Google',
    displayName: 'Google Gemini Services',
    userFacingName: 'Research Continuity Services',
    enables: 'Backup capabilities for research workflows during primary service degradation',
    statusPageUrl: 'https://status.cloud.google.com',
    apiEndpoint: 'https://status.cloud.google.com/incidents.json',
    color: '#4285f4',
    priority: 'secondary',
    dependsOn: ['aws'],
    impacts: 'Fallback services unavailable, reduced service redundancy',
    models: ['Gemini Flash', 'Gemini Flash Light', 'Gemini 2.0 Flash'],
    role: 'fallback',
  },
  {
    id: 'exa',
    name: 'Exa',
    displayName: 'Exa Search',
    userFacingName: 'Web Intelligence Service',
    enables: 'Primary web search, data enrichment, source verification for research',
    statusPageUrl: 'https://status.exa.ai',
    apiEndpoint: 'https://status.exa.ai/api/v2/summary.json',
    color: '#3b82f6',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Web data collection degraded, research quality reduced',
  },
  {
    id: 'brave',
    name: 'Brave',
    displayName: 'Brave Search',
    userFacingName: 'Search Continuity Service',
    enables: 'Backup web search capabilities, source diversity',
    statusPageUrl: 'https://status.brave.app',
    apiEndpoint: 'https://status.brave.app',
    color: '#fb542b',
    priority: 'secondary',
    dependsOn: ['aws'],
    impacts: 'Reduced search redundancy and source diversity',
    role: 'fallback',
  },
];
