import { Provider } from './types';

export const PROVIDERS: Provider[] = [
  {
    id: 'aws',
    name: 'AWS',
    displayName: 'AWS Infrastructure',
    userFacingName: 'Platform Infrastructure',
    enables: 'Document storage, API gateway, processing pipeline',
    statusPageUrl: 'https://health.aws.amazon.com/health/status',
    apiEndpoint: 'https://status.aws.amazon.com/data.json',
    color: '#ff9900',
    priority: 'primary',
    impacts: 'All services may experience slowdowns or interruptions',
    regions: ['Singapore (ap-southeast-1)', 'Mumbai (ap-south-1)'],
    services: ['S3 Storage', 'Lambda Functions', 'API Gateway'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    displayName: 'OpenAI GPT Services',
    userFacingName: 'Primary Research Service',
    enables: 'Research generation, data synthesis, conversational AI',
    statusPageUrl: 'https://status.openai.com',
    apiEndpoint: 'https://status.openai.com/api/v2/summary.json',
    color: '#10a37f',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Research generation and data synthesis unavailable',
    models: ['GPT-5', 'GPT-5 mini'],
    role: 'primary',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    displayName: 'Anthropic Claude Services',
    userFacingName: 'Advanced Analysis Service',
    enables: 'Advanced reasoning, research orchestration, quality validation',
    statusPageUrl: 'https://status.anthropic.com',
    apiEndpoint: 'https://status.anthropic.com/api/v2/summary.json',
    color: '#d4a574',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Advanced reasoning and research orchestration unavailable',
    models: ['Claude Sonnet 4', 'Claude Sonnet 4.5', 'Claude Haiku 5'],
    role: 'primary',
  },
  {
    id: 'google',
    name: 'Google',
    displayName: 'Google Gemini Flash',
    userFacingName: 'Research Continuity Service',
    enables: 'Continuity service when primary models are degraded',
    statusPageUrl: 'https://status.cloud.google.com',
    apiEndpoint: 'https://status.cloud.google.com/incidents.json',
    color: '#4285f4',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Fallback service unavailable, reduced redundancy',
    models: ['Gemini Flash'],
    role: 'fallback',
  },
  {
    id: 'exa',
    name: 'Exa',
    displayName: 'Exa AI',
    userFacingName: 'Data Intelligence Service',
    enables: 'Live data enrichment, source verification',
    statusPageUrl: 'https://status.exa.ai',
    apiEndpoint: 'https://status.exa.ai/api/v2/summary.json',
    color: '#3b82f6',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Reduced research quality, limited source verification',
  },
  {
    id: 'brave',
    name: 'Brave',
    displayName: 'Brave Search',
    userFacingName: 'Web Discovery Service',
    enables: 'Web search capabilities, source diversity',
    statusPageUrl: 'https://status.brave.app',
    apiEndpoint: 'https://status.brave.app',
    color: '#fb542b',
    priority: 'primary',
    dependsOn: ['aws'],
    impacts: 'Reduced search source diversity',
  },
];
