import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

/**
 * POST /api/customer-support
 * Customer chat widget submissions - with a dash of humor!
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    const body = await request.json();
    const {
      name,
      email,
      message,
      attachments, // Array of file URLs uploaded to storage
    } = body;

    // Validation with playful messages
    if (!name || !name.trim()) {
      return NextResponse.json(
        {
          error: 'Name is required',
          humorousMessage: 'We need to know what to call you! Unless you prefer "Hey You" 👋'
        },
        { status: 400 }
      );
    }

    if (!email || !email.trim()) {
      return NextResponse.json(
        {
          error: 'Email is required',
          humorousMessage: 'How else will we send you our strongly worded response? 📧'
        },
        { status: 400 }
      );
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        {
          error: 'Invalid email format',
          humorousMessage: 'That email looks a bit sus... Mind double-checking? 🤔'
        },
        { status: 400 }
      );
    }

    if (!message || !message.trim()) {
      return NextResponse.json(
        {
          error: 'Message is required',
          humorousMessage: 'We love telepathy, but maybe just type it out? 🔮'
        },
        { status: 400 }
      );
    }

    // Format ticket description with message and attachments
    let ticketDescription = `<div style="font-family: system-ui, -apple-system, sans-serif;">
      <p style="font-size: 16px; line-height: 1.6; margin-bottom: 20px;">${message.replace(/\n/g, '<br>')}</p>
    </div>`;

    if (attachments && attachments.length > 0) {
      ticketDescription += '\n\n<hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">\n<h4 style="color: #374151; font-size: 14px; font-weight: 600; margin-bottom: 10px;">📎 Attachments:</h4>\n<ul style="list-style: none; padding: 0;">';
      attachments.forEach((attachment: { name: string; url: string; type: string }) => {
        if (attachment.type.startsWith('image/')) {
          ticketDescription += `\n<li style="margin-bottom: 10px;"><strong>${attachment.name}</strong><br><img src="${attachment.url}" alt="${attachment.name}" style="max-width: 600px; margin: 10px 0; border: 1px solid #ddd; border-radius: 8px;"></li>`;
        } else {
          ticketDescription += `\n<li style="margin-bottom: 8px;"><a href="${attachment.url}" target="_blank" style="color: #3b82f6; text-decoration: none;">${attachment.name}</a></li>`;
        }
      });
      ticketDescription += '\n</ul>';
    }

    // Add customer info
    ticketDescription += `\n\n<hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
    <div style="background: #f9fafb; padding: 12px; border-radius: 6px; font-size: 13px;">
      <p style="margin: 4px 0;"><strong style="color: #6b7280;">Customer:</strong> ${name}</p>
      <p style="margin: 4px 0;"><strong style="color: #6b7280;">Email:</strong> <a href="mailto:${email}" style="color: #3b82f6;">${email}</a></p>
      <p style="margin: 4px 0;"><strong style="color: #6b7280;">Source:</strong> Customer Chat Widget</p>
    </div>`;

    // Create ticket with customer_chat source
    const { data: ticket, error: ticketError} = await supabase
      .from('tickets')
      .insert({
        ticket_number: null, // Auto-generated by trigger
        title: message.substring(0, 100), // First 100 chars as title
        description: ticketDescription,
        status: 'open',
        priority: 'medium',
        category: 'general', // Must be one of: general, bug, feature, account, technical (lowercase!)
        user_name: name,
        user_email: email,
        created_by: user?.id || null,
        source: 'customer_chat',
        organization: 'Customer', // Mark as customer ticket
      })
      .select('ticket_id, ticket_number')
      .single();

    if (ticketError) {
      console.error('Error creating customer ticket:', JSON.stringify(ticketError, null, 2));
      throw ticketError;
    }

    // Notify all super admins
    try {
      const { data: superAdmins } = await supabase
        .from('users')
        .select('id')
        .eq('is_super_admin', true);

      if (superAdmins && superAdmins.length > 0) {
        const notifications = superAdmins.map(admin => ({
          user_id: admin.id,
          entity_type: 'ticket',
          entity_id: ticket.ticket_id,
          entity_title: message.substring(0, 100),
          notification_type: 'support_ticket',
          actor_id: user?.id || null,
          title: `💬 New Customer Message from ${name}`,
          message: message.substring(0, 200),
          action_url: `/support/admin/customer-support?id=${ticket.ticket_id}`,
          priority_score: 80, // Medium-high priority for customer messages
          thread_key: `customer_ticket:${ticket.ticket_id}`,
          status: 'unread'
        }));

        await supabase.from('notifications').insert(notifications);
      }
    } catch (notifError) {
      console.error('Error creating notifications for customer ticket:', notifError);
      // Don't fail ticket creation if notifications fail
    }

    // Return success with humorous messages
    const humorousResponses = [
      {
        title: "Message received! 🎉",
        message: "Your message has been successfully delivered to our inbox where our team of 2.5 people (Harsha is part-time) will get right on it!",
        subtitle: "We promise someone will actually read this... eventually 😅"
      },
      {
        title: "Victory! ✨",
        message: "We've dispatched a horde of problem-solvers (all 3 of them) to tackle your query!",
        subtitle: "They're highly caffeinated and ready to help ☕"
      },
      {
        title: "Success! 🚀",
        message: "Your ticket has landed in our system faster than a cat video goes viral!",
        subtitle: "Our massive team is assembling as we speak 🎯"
      },
      {
        title: "Got it! 👍",
        message: "Message received! We're waking up our crack team of support ninjas from their power nap...",
        subtitle: "They'll be with you shortly (probably) 🥷"
      }
    ];

    const randomResponse = humorousResponses[Math.floor(Math.random() * humorousResponses.length)];

    return NextResponse.json({
      success: true,
      ticketId: ticket.ticket_id,
      ticketNumber: ticket.ticket_number,
      humor: randomResponse,
      message: 'Customer ticket created successfully'
    });

  } catch (error: any) {
    console.error('Error creating customer support ticket:', error);
    return NextResponse.json(
      {
        error: 'Failed to send message',
        humorousMessage: 'Oops! Our servers just had a hiccup. Mind trying again? 🤷‍♂️',
        technicalDetails: error.message
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/customer-support
 * Retrieve customer's own tickets by email (for tracking)
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const email = searchParams.get('email');

    if (!email) {
      return NextResponse.json(
        { error: 'Email parameter is required' },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    const { data: tickets, error } = await supabase
      .from('tickets')
      .select('ticket_id, ticket_number, title, status, priority, created_at, updated_at')
      .eq('user_email', email)
      .eq('source', 'customer_chat')
      .order('created_at', { ascending: false });

    if (error) throw error;

    return NextResponse.json({
      success: true,
      tickets: tickets || [],
      count: tickets?.length || 0
    });

  } catch (error: any) {
    console.error('Error fetching customer tickets:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tickets', message: error.message },
      { status: 500 }
    );
  }
}
